name: Renovate
on:
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '*/11 * * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Show Repo
        run: echo "run on ${{ github.repository }}"
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.3
        with:
          configurationFile: .github/workflows/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
